config/routes.rb
Rails.application.routes.draw do
  resources :restaurants, only: %i[index new show create] do
    resources :reviews, only: %i[new create]
	end
end

# get '/restaurants', to: 'restaurants#index', as: :restaurants

# # Add new restaurant (new action/create action)
# get 'restaurants/new', to: 'restaurants#new', as: :new_restaurant
# post '/restaurants', to: 'restaurants#create'

# # Read one
# get 'restaurants/:id', to: 'restaurants#show', as: :restaurant

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORY = ['chinese', 'italian', 'japanese', 'french', 'belgian']
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true
  validates :category, inclusion: { in: CATEGORY }
end

app/models/review.rb
class Review < ApplicationRecord
  NUMBER = [0, 1, 2, 3, 4, 5]
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, inclusion: { in: NUMBER }
  validates :rating, numericality: { only_integer: true }
  validates :rating, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant

    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
    # and now it permit is true (protect our form)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_card.html.erb
<div class="card-product">
  <%= image_tag "http://source.unsplash.com/featured/?restaurant&#{rand(1000)}/800x333" %>
  <div class="card-product-infos">
    <h2><%= restaurant.name %></h2>
    <p><%= restaurant.category %></p>
  </div>
  <%= link_to '', restaurant_path(restaurant), class: 'card-product-link'  %>
</div>

app/views/restaurants/index.html.erb
<%# <h1>Restaurants</h1>
<ul>
  <% @restaurants.each do |restaurant| %>
    <%# <li><%= restaurant.name %>
  <%# <% end %>
<%# </ul> %>


<div class="container mt-3">
  <div class="d-flex justify-content-between align-items-center">
    <h1>Restaurants</h1>
    <%= link_to new_restaurant_path, class: 'text-dark' do %>
      <i class="fas fa-plus-square btn-light"></i>
    <% end %>
  </div>
  <div class="cards">
    <% @restaurants.each do |restaurant| %>
      <%= render 'restaurants/card', restaurant: restaurant %>
    <% end %>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="container mt-3">
  <h1>Add a New Restaurant</h1>
  <%= simple_form_for @restaurant do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category, collection: Restaurant::CATEGORY.sort, include_blank: false %>
    <%= f.submit 'Submit', class: 'btn btn-primary mt-2' %>
  <% end %>
</div>

app/views/restaurants/show.html.erb
<div class="container mt-3">
    <div class="d-flex justify-content-between">
      <h1><%= @restaurant.name %></h1>
      <%= link_to '<- Back', restaurants_path, class: 'text-primary text-decoration-none'%>
    </div>

  <div class="card mb-3" style="max-width: 540px;">
    <div class="row g-0">
      <div class="col-md-4">
        <img src= "http://source.unsplash.com/featured/?restaurant&#{rand(1000)}/800x333" class="img-fluid rounded-start" alt="...">
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title"><h1><%= @restaurant.name %></h1></h5>
          <p class="card-text"><%= @restaurant.address %></p>
          <p class="card-text"><small class="text-muted"><%= @restaurant.phone_number %></small></p>
        </div>
      </div>
    </div>
  </div>

    <h3> Reviews <%= link_to '+',	new_restaurant_review_path(@restaurant)%> </h3>
    <ul>
      <% @restaurant.reviews.each do |review| %>
        <li>
        <% review.rating.times do %>
          <i class="fas fa-star"></i>
        <% end %>
        <% (5 - review.rating).times do %>
          <i class="far fa-star"></i>
        <% end %><br>
        <%= review.content %></li>
      <% end %>
    </ul>
</div>

<%# </li><%= link_to '+', review_path(review), data: {turbo_method: :delete, turbo_confirm: 'Delete Review?'} %>

        <%# <p>Phone number: <%= @restaurant.phone_number %>
        <%# <p>Address: <%= @restaurant.address %>
        <%# <p>Category: <%= @restaurant.category %>

app/views/reviews/new.html.erb
<div class="container mt-3">
  <h1>Add a Review</h1>
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating, collection: Review::NUMBER.sort, include_blank: false %>
    <%= f.submit 'Submit', class: 'btn btn-primary mt-2' %>
  <% end %>
</div>